version: '3'

services:
    nginx:
        container_name: nginxxx
        image: nginx:latest
        ports:
            - "8080:80"
            - "443:443"
        links:
            - php
        volumes:
            - ./:/var/www
            - ./hosts:/etc/nginx/conf.d
    php:
        build:
            context: .
            dockerfile: docker/Fpm.Dockerfile
        volumes:
            - ./:/var/www
        links:
            - mysql
    mysql:
        image: mysql:latest
        ports:
            - 33061:3306
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: true
            MYSQL_DATABASE: iq_test
